<?php
$films = array(
    array(
        'titreFilm' => 'Retour vers le futur',
        'nomCreateur' => 'Zemeckis Robert',
        'anneeFilm' => strtotime('03-07-1985'),
        'genreFilm' => 'Science-fiction',
        'dureeFilm' => 116,
        'descriptionFilm' => "En 1985, Marty, un adolescent comme les autres, mène une existence qu'il juge morne et ennuyeuse. Heureusement, il est épris de la jolie Jennifer et entretient une profonde amitié avec Doc, un savant fou qui prétend avoir inventé une machine à explorer le temps. Un jour, Doc invite Marty à l'essayer. Mais ils sont surpris par des terroristes. Doc est abattu tandis que Marty met l'engin en marche et se retrouve en 1955.",
        'afficheFilm' => "https://fr.web.img2.acsta.net/medias/nmedia/18/35/91/26/18686482.jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Le Seigneur des Anneaux : La communauté de l'anneau",
        'nomCreateur' => 'George Lucas',
        'anneeFilm' => strtotime('19-12-2001'),
        'genreFilm' => 'Fantasy',
        'dureeFilm' => 178,
        'descriptionFilm' => "Frodon reçoit l'Anneau de son oncle Bilbo. Sa vie et son monde sont pourtant en danger, car cet anneau appartient à Sauron, le maître des ténèbres.",
        'afficheFilm' => "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGX05V2LQ/image?locale=fr-fr&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => 'La Guerre des Etoiles',
        'nomCreateur' => 'George Lucas',
        'anneeFilm' => strtotime('25-05-1977'),
        'genreFilm' => 'Science-fiction',
        'dureeFilm' => 121,
        'descriptionFilm' => "Dans une galaxie lointaine, l'univers est dominé par l'Empire galactique avec à sa tête le sombre et impitoyable Dark Vador. Mais la révolte gronde, l'Alliance rebelle menée par la princesse Leia, s'empare des plans de l'Etoile Noire, la base secrète de l'Empire. Avant d'être capturée par les forces impériales, la jeune princesse dissimule les plans de l'Etoile Noire à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, les deux robots s'échouent sur la planète Tatooine et terminent leur quête chez le jeune Luke Skywalker. Rêvant de devenir pilote, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine...",
        'afficheFilm' => "https://fr.web.img6.acsta.net/medias/nmedia/18/35/41/59/18422600.jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Harry Potter à l'école des sorciers",
        'nomCreateur' => 'Chris Columbus',
        'anneeFilm' => strtotime('16-11-2001'),
        'dureeFilm' => 152,
        'genreFilm' => 'Fantastique',
        'descriptionFilm' => "Orphelin, Harry Potter est élevé par son oncle et sa tante qui l'obligent à vivre dans un placard. Ces derniers, lui cachent qu'il est en fait fils de sorciers et que sa place est à Poudlard, la prestigieuse école de magie. Le jour de ses 11 ans, un géant nommé Hagrid lui révèle enfin la vérité. Après s'être équipé comme il se doit, Harry fait sa rentrée à Poudlard et débute très vite une nouvelle vie.",
        'afficheFilm' => "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZL5XQS/image?locale=fr-fr&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Jurassic Park",
        'nomCreateur' => 'Steven Spielberg',
        'anneeFilm' => strtotime('11-06-1993'),
        'dureeFilm' => 127,
        'genreFilm' => 'Science-fiction',
        'descriptionFilm' => "Sur une île au large du Costa Rica, des scientifiques, financés par le milliardaire John Hammond, ont réussi à cloner des animaux préhistoriques. Leur découverte a permis de créer un parc d'attractions peuplé de dinosaures. Avant l'ouverture au public, Hammond demande à Alan et Ellie, deux paléontologues de renom, de cautionner son projet. Mais lors de la première inspection, le système de sécurité se détraque.",
        'afficheFilm' => "https://i.pinimg.com/736x/63/85/bd/6385bdfd1630be0e114b22f680fa5e0c.jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Le Roi Lion",
        'nomCreateur' => 'Roger Allers',
        'anneeFilm' => strtotime('15-06-1994'),
        'dureeFilm' => 89,
        'genreFilm' => 'Animation',
        'descriptionFilm' => "Dans la savane africaine, Simba, le fils du roi lion Mufasa, vient de naître et il est présenté à tous les animaux sur lesquels il est appelé à régner un jour. Mais si la liesse s'empare de la plupart des animaux, Scar, le frère de Mufasa, qui voit une fois de plus le trône lui échapper, rumine dans l'ombre et prépare sa vengeance.",
        'afficheFilm' => "https://i1.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/06/le-roi-lion-a.jpg?fit=373%2C499&ssl=1",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "L'empire contre-attaque",
        'nomCreateur' => 'Irvin Kershner',
        'anneeFilm' => strtotime('21-05-1980'),
        'dureeFilm' => 124,
        'genreFilm' => 'Science-fiction',
        'descriptionFilm' => "Malgré la destruction de l'Etoile noire, l'Empire règne toujours sur la galaxie. Un groupe de l'Alliance rebelle, mené par la princesse Leia se réfugie sur la planète glacée de Hoth. Après avoir subi un assaut des troupes impériales, Leia, Han Solo, Chewbacca et C-3P0 parviennent à s'échapper et se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. De son côté, Luke s'envole pour Dagobah afin d'apprendre l'art des Jedi avec le maître Yoda.",
        'afficheFilm' => "https://fr.web.img4.acsta.net/medias/nmedia/00/02/44/28/empire.jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Le Seigneur des anneaux : Le Retour du roi",
        'nomCreateur' => 'Peter Jackson',
        'anneeFilm' => strtotime('01-12-2003'),
        'dureeFilm' => 201,
        'genreFilm' => 'Fantasy',
        'descriptionFilm' => "Guidés par Gollum, Frodon et Sam continuent leur périple vers la montagne du destin, tandis que Gandalf et ses compagnons se retrouvent à Isengard.",
        'afficheFilm' => "https://fr.web.img3.acsta.net/medias/nmedia/18/35/14/33/18366630.jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Le Seigneur des anneaux : Les Deux Tours",
        'nomCreateur' => 'Peter Jackson',
        'anneeFilm' => strtotime('18-12-2002'),
        'dureeFilm' => 178,
        'genreFilm' => 'Fantasy',
        'descriptionFilm' => "Frodon et Sam continuent leur voyage vers Mordor pour détruire l'anneau de Sauron. Aragorn, Gimli et Legolas partent pour sauver leurs amis hobbits.",
        'afficheFilm' => "https://fr.web.img6.acsta.net/medias/nmedia/00/02/54/95/affiche2.jpg",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Retour vers le futur 2",
        'nomCreateur' => 'Robert Zemeckis',
        'anneeFilm' => strtotime('22-11-1989'),
        'dureeFilm' => 108,
        'genreFilm' => 'Science-fiction',
        'descriptionFilm' => "En 1985, Marty McFly a retrouvé sa famille et sa petite amie après un voyage mouvementé dans le passé. Surgit alors Doc Brown, au volant de sa machine à explorer le temps. Il lui enjoint de le suivre dans le futur, en l'an 2015, pour secourir son fils tombé sous la coupe du sinistre Biff Tannen.",
        'afficheFilm' => "https://i1.wp.com/www.filmspourenfants.net/wp-content/uploads/2018/07/retour-vers-le-futur-2-a.jpg?fit=555%2C797&ssl=1",
        'proposition' => 0,
    ),
    array(
        'titreFilm' => "Asterix et Obelix : Mission Cleopatre",
        'nomCreateur' => 'Alain Chabat',
        'anneeFilm' => strtotime('30-01-2002'),
        'dureeFilm' => 107,
        'genreFilm' => 'Comedie',
        'descriptionFilm' => "A Alexandrie, en 52 av. J.-C., Cléopâtre, désireuse de prouver la supériorité du peuple égyptien, relève le défi lancé par l'Empereur romain Jules César : construire un palais en trois mois ! Pour ce faire, Cléopâtre fait appel à l'architecte Numérobis. S'il réussit, elle le couvrira d'or. S'il échoue, elle le jettera aux crocodiles. Celui-ci, conscient du défi à relever, cherche de l'aide auprès de son vieil ami Panoramix. Le druide fait le voyage en Égypte avec Astérix et Obélix. De son côté, Amonbofis, l'architecte officiel de Cléopâtre, jaloux que la reine ait choisi Numérobis pour construire le palais, va tout mettre en œuvre pour faire échouer son concurrent.",
        'afficheFilm' => "https://fr.web.img3.acsta.net/medias/nmedia/00/02/39/29/aff_asterix.jpg",
        'proposition' => 0,
    ),
);
